// Pino redact paths — these fields are redacted from all log output
export const PINO_REDACT_PATHS = [
  "password",
  "appPassword",
  "token",
  "secret",
  "encryptedSecretBlob",
  "encrypted_secret_blob",
  "iv",
  "authTag",
  "auth_tag",
  "passwordHash",
  "password_hash",
  "masterKey",
  "jwtSecret",
  "authorization",
  "req.headers.authorization",
  "request.headers.authorization",
  "body.password",
  "body.appPassword",
  "*.password",
  "*.appPassword",
  "*.token",
  "*.secret",
];
